vim.loader.enable()
require("lazynvim-init")
require("options")
require("keymaps")


-- todo: reconfig the clangd config.yaml file, if use clangd with mason 
--[[
local filePath = vim.fn.stdpath('config')..'/../clangd/config.yaml'

local file = io.open(filePath,'w')
io.output(file)
io.write(
[[
# This file was generated by Qt Creator and will be overwritten unless you remove this line.
Hover:
  ShowAKA: Yes
Diagnostics:
  UnusedIncludes: Strict
CompileFlags:
  Add:
    --target=x86_64-w64-windows-gnu
]]
-- )
-- io.close()
--]]
